---

# If Jessie
- name: Installs dependencies (Jessie)
  ansible.builtin.apt:
    name: fbi
  when: ansible_distribution_major_version|int <= 7

- name: Copies in splash screen
  ansible.builtin.copy:
    src: splashscreen.png
    dest: /etc/splashscreen.png
    mode: "0644"
    owner: root
    group: root
  when: ansible_distribution_major_version|int <= 7

- name: Copies in rc script
  ansible.builtin.copy:
    src: asplashscreen
    dest: /etc/init.d/asplashscreen
    mode: "0755"
  when: ansible_distribution_major_version|int <= 7

- name: Enables asplashscreen
  ansible.builtin.command: update-rc.d asplashscreen defaults
  args:
    creates: /etc/rcS.d/S01asplashscreen
  when: ansible_distribution_major_version|int <= 7

# If not Jessie
- name: Remove older versions
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/splashscreen.jpg
    - /etc/init.d/asplashscreen
  when: ansible_distribution_major_version|int > 7

- name: Get stat of asplashscreen
  ansible.builtin.stat:
    path: /etc/rcS.d/S01asplashscreen
  register: asplashscreen_path
  when: ansible_distribution_major_version|int > 7

- name: Disable asplashscreen
  ansible.builtin.command: update-rc.d asplashscreen remove
  when: ansible_distribution_major_version|int > 7
  changed_when: asplashscreen_path.stat.exists

- name: Installs dependencies (not Jessie)
  ansible.builtin.apt:
    name:
      - plymouth
      - plymouth-themes
      - plymouth-label
  when: ansible_distribution_major_version|int > 7

- name: Remove the old Plymouth scripts
  ansible.builtin.file:
    state: absent
    path: /usr/share/plymouth/themes/screenly/
    owner: root
    group: root

- name: Copies plymouth theme
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/share/plymouth/themes/anthias/
    mode: "0644"
    owner: root
    group: root
  with_items:
    - anthias.plymouth
    - anthias.script
    - splashscreen.png
  when: ansible_distribution_major_version|int > 7

- name: Get current plymouth theme
  ansible.builtin.command: plymouth-set-default-theme
  register: plymouth_theme
  changed_when: false
  when: ansible_distribution_major_version|int > 7

- name: Set splashscreen
  ansible.builtin.command: plymouth-set-default-theme -R anthias
  when: ansible_distribution_major_version|int > 7
  changed_when: plymouth_theme.stdout != "anthias"

- name: Set plymouthd.default
  ansible.builtin.copy:
    src: plymouthd.default
    dest: /usr/share/plymouth/plymouthd.defaults
    mode: "0644"
    owner: root
    group: root
  when: ansible_distribution_major_version|int > 7

- name: Copy to plymouthd.conf
  ansible.builtin.copy:
    src: plymouthd.default
    dest: /etc/plymouth/plymouthd.conf
    mode: "0644"
    owner: root
    group: root
  when: ansible_distribution_major_version|int > 7

- name: Force overwrite Docker container splash screens
  ansible.builtin.shell: |
    # Find running containers and copy our splash screen
    docker ps --format "table {{ '{{' }}.Names{{ '}}' }}" | grep anthias | while read container; do
      if docker exec $container test -d /usr/share/plymouth/themes/anthias; then
        docker cp ansible/roles/splashscreen/files/splashscreen.png $container:/usr/share/plymouth/themes/anthias/splashscreen.png
      fi
      if docker exec $container test -d /etc; then
        docker cp ansible/roles/splashscreen/files/splashscreen.png $container:/etc/splashscreen.png
      fi
      if docker exec $container test -d /app/static/img; then
        docker cp static/img/standby.png $container:/app/static/img/standby.png
      fi
    done
  ignore_errors: yes
  when: ansible_distribution_major_version|int > 7

- name: Create systemd service to fix containers after boot
  ansible.builtin.copy:
    dest: /etc/systemd/system/fix-anthias-images.service
    content: |
      [Unit]
      Description=Fix Anthias Container Images
      After=docker.service
      Wants=docker.service
      
      [Service]
      Type=oneshot
      ExecStartPre=/bin/sleep 60
      ExecStart=/bin/bash -c 'CONTAINER=$(docker ps --format "{{ '{{' }}.Names{{ '}}' }}" | grep server | head -1); if [ ! -z "$CONTAINER" ]; then docker cp /home/{{ ansible_user }}/screenly/static/img/standby.png $CONTAINER:/usr/src/app/static/img/standby.png; docker restart $CONTAINER; fi'
      RemainAfterExit=yes
      
      [Install]
      WantedBy=multi-user.target
  when: ansible_distribution_major_version|int > 7

- name: Enable fix service
  ansible.builtin.systemd:
    name: fix-anthias-images.service
    enabled: yes
    daemon_reload: yes
  when: ansible_distribution_major_version|int > 7